### ISSUE TITLE
Training with RLlib

### ISSUE THREAD

**Issue by Maxwell2017** [alex-petrenko/sample-factory#104]
Hi @alex-petrenko ，I have two questions about training with RLlib:
1.do you know the DQN training hyperparameters that can works well in other scenes of vizdoom (except basic and health gethering)? 
2.Can this  [yaml](https://github.com/alex-petrenko/sample-factory/blob/master/benchmarks/rllib/rllib_fps_benchmark/dmlab-impala-fps.yaml) file be used in all scenarios of dmlab?
Any feedback or help/tips would be greatly appreciated!

**Comment by alex-petrenko** [comment]
Hi @Maxwell2017 
Sorry for the late reply. Sorry, I don't know much about training DQN in RLLIB, your best bet is to experiment or copy settings from one of the successful experiments in RLLIB repo. Take a look here, I think starting with their Atari parameters is better than starting from scratch https://github.com/ray-project/ray/tree/master/rllib/tuned_examples/dqn

As for the yaml file, this will only work with the dmlab_benchmark environment that is registered in the starting script. https://github.com/alex-petrenko/sample-factory/blob/master/benchmarks/rllib/train_rllib.py

See  register_dmlab_envs_rllib function there

**Comment by Maxwell2017** [comment]
Yeah，i see register_dmlab_envs_rllib function，Now I want to use RLlib to train the dmlab agent based on IMPALA algorithm. I should be able to use your [environment ](https://github.com/alex-petrenko/sample-factory/blob/master/envs/dmlab/dmlab_gym.py) too ? Is there anything that needs to be modified?
I noticed that the default method you are using is APPO, I think at least [here](https://github.com/alex-petrenko/sample-factory/blob/d80dcaf54ddb2a554e3b344c456ffd65cb879425/algorithms/utils/arguments.py#L104) needs to be modified. I am not sure if this [function](https://github.com/alex-petrenko/sample-factory/blob/d80dcaf54ddb2a554e3b344c456ffd65cb879425/algorithms/utils/arguments.py#L12) is useful for me? I haven`t seen algo_class is used in funtion [arg_parser](https://github.com/alex-petrenko/sample-factory/blob/d80dcaf54ddb2a554e3b344c456ffd65cb879425/algorithms/utils/arguments.py#L27)
Waiting for your reply~ @alex-petrenko

**Comment by alex-petrenko** [comment]
I think you might be confusing the SampleFactory codebase and what's inside the benchmarks folder.
It is just a complementary folder containing the code that we used to measure performance of other frameworks. It was never meant to be the source of information on how to train with RLLIB. I think it is much better to ask on RLLIB github, to be honest, as I am no expert in RLLIB training.

Answering your questions:
1) you can train with IMPALA, for that you need to specify IMPALA algorithm in the yaml script like here: https://github.com/alex-petrenko/sample-factory/blob/master/benchmarks/rllib/rllib_fps_benchmark/dmlab-impala-fps.yaml
No need to modify any Sample Factory code for that.

2) you can definitely use my DMLab wrappers, feel free to copy-paste them to your codebase or use as-is.

3) this function https://github.com/alex-petrenko/sample-factory/blob/d80dcaf54ddb2a554e3b344c456ffd65cb879425/algorithms/utils/arguments.py#L12 is not useful to you if you're training with RLLIB. 99% of Sample Factory codebase has nothing to do with RLLIB, again, there are only a couple of example scripts

**Comment by Maxwell2017** [comment]
Thanks for your kindly reply, I will try it（dmlab env）as soon as possible ：）

**Comment by Maxwell2017** [comment]
Thanks for your kindly reply, I will try it（dmlab env）as soon as possible ：）
