### ISSUE TITLE
RTX 30xx compatibility

### ISSUE THREAD

**Issue by alex404** [alex-petrenko/sample-factory#115]
Hello, I was wondering if you could update the environment.yaml file to more recent versions of pytorch and cuda (i.e. 1.9.* and 11.*) to "officially" support RTX 30xx cards.

I have an AMD 5950x and an RTX 3090, and I've been able to get sample-factory running with vizdoom by installing vizdoom with pip in a conda environment and running sample-factory straight from the repository. The performance is great (I'm getting about 100K FPS), but I guess because I'm not using your vizdoom branch I'm locked out of the multi-agent framework. I'm also hoping to rely on sample-factory for a longer-term research project, and I worry that other issues might arise if I have to use it in this "unofficial" way.

Thanks for your hard work. This is an impressive piece of software!

**Comment by alex-petrenko** [comment]
Also, for 100K FPS, how many CPU cores are you using?
And what are the parameters such as number of workers, environments per worker, and batch size?

**Comment by alex-petrenko** [comment]
Sounds good. I think I generally found batch sizes around 2048 to be more
sample efficient, but overall your command line looks okay.
It is also advised to set the num_workers to the number of logical CPU
cores you have.

сб, 16 окт. 2021 г. в 00:47, Sacha Sokoloski ***@***.***>:

**Comment by alex-petrenko** [comment]
> Thanks for your reply and general advice. I haven't actually tried to run the multi-agent simulations yet because we haven't needed for our project, but it's good to hear that you think it should be generally supported without using your fork. If you have the time I think it would be helpful to update the README.md, because right now it strongly encourages new users to use your environment.yml and vizdoom fork, which isn't viable for people with the newest generation of cards, and doesn't seem strictly necessary.
> 
> Anyway, running
> 
> `python -m sample_factory.algorithms.appo.train_appo --env=doom_benchmark --algo=APPO --env_frameskip=4 --use_rnn=True --num_workers=36 --num_envs_per_worker=24 --num_policies=1 --ppo_epochs=1 --rollout=32 --recurrence=32 --batch_size=8192 --wide_aspect_ratio=False --experiment=doom_5950x_RTX3090_bench --policy_workers_per_policy=2`
> 
> for half an hour or so resulting in the program spitting out `FPS: 100948.4`. While running it maxes out the 16-cores/32 threads of my CPU, and seems to run around 50-60% utilization on my GPU.
> 
> I'll let you know when I get around to trying out the multi-agent simulations, but I'm pretty swamped for the next month, so it'll be a bit of time.
> 
> Thanks again!

I updated the README which now recommends installing VizDoom>=1.1.9 from PyPI. Everything works on it including the multi-agent stuff.

I still found that my environment.yml gives better performance than starting from an empty conda env and installing sample factory in it. I believe this is due to some performance regressions in the latest versions of MKL or Numpy. So I kept both options for now. Other than performance, everything seems to work with just `pip install`.
