### ISSUE TITLE
Can we train maddpg-pytorch on sample-factory?

### ISSUE THREAD

**Issue by kailashg26** [alex-petrenko/sample-factory#117]
Hello, I'm checking for simulators to execute the multi agent algorithm (maddpg [https://github.com/shariqiqbal2810/maddpg-pytorch]). So, can anyone help me if I can execute the pytorch maddpg on sample-factory?

**Comment by alex-petrenko** [comment]
Hello! SampleFactory is not a simulator, but a reinforcement learning algorithm.
If you're looking for fast simulators, check out our Megaverse: https://www.megaverse.info/ It supports multi-agent training at 10^5-10^6 samples per second. It should be a suitable platform to test multi-agent algorithms, including maddpg.

**Comment by kailashg26** [comment]
Hello, Is there any documentation on how to port maddpg on megaverse?
Thanks,
Kailash

**Comment by alex-petrenko** [comment]
Megaverse is the RL environment. I believe it should be similar to using any other RL environment with this algorithm. There is not documentation fort this specific algorithm
