### ISSUE TITLE
Adding custom maps to doom environment

### ISSUE THREAD

**Issue by alex404** [alex-petrenko/sample-factory#118]
Hello,

I'm wondering what you would think is the most "idiomatic" way to run sample-factory with the vizdoom environment family, but a custom wad and cfg file. I notice in doom_utils.py there's a hard coded DOOM_ENVS variable that specifies the pre-built environments, which seems like it would be straightforward to modify, but I'd prefer not have to modify sample-factory directly for my own project (I'd rather be able to pull it in with `pip install sample-factory`). On the other hand in your `train_custom_env_custom_model.py` file I could specify a whole new environment, but I'd rather not lose any of the vizdoom functionality.

As a side note, for some reason when I run `pip install sample-factory` it doesn't copy the scenario folder into my conda directory, and so I can't run the example commands from your README.md. Not sure if this is me doing something foolish.

Thanks!

**Comment by alex-petrenko** [comment]
> I'd prefer not have to modify sample-factory directly for my own project (I'd rather be able to pull it in with pip install sample-factory)

You can modify DOOM_ENVS list directly in your custom experiment script.
In the latest release (1.121.2) I added a helper function `register_additional_doom_env` in doom_utils.py that does exactly that.

I've also added a new example script `sample_factory_examples/train_custom_vizdoom_env.py` that demonstrates how to use this API. Basically to specify a custom Doom env you need:
* env name
* .cfg file absolute path (.wad usually in the same dir)
* action space - perhaps on of the existing ones will suit you, look at the other doom_spec definitions
* reward scaling, default_timeout, wrappers and other options of DoomSpec class

Let me know if this works for you.

> As a side note, for some reason when I run pip install sample-factory it doesn't copy the scenario folder into my conda directory, and so I can't run the example commands from your README.md. Not sure if this is me doing something foolish.

Oops, sorry about that. Looks like it broke some time in the future, despite these paths being in my MANIFEST template. I think I fixed it in the latest release (1.121.2).
Thank you for reporting this!

**Comment by alex404** [comment]
Thanks! I'm just working on a few things around this project at the moment, but I'll test this functionality out next week and report back.

**Comment by alex404** [comment]
Works like a charm!
