### ISSUE TITLE
How to generate fixed, deterministic episode on dmlab30? 

### ISSUE THREAD

**Issue by khy0809** [alex-petrenko/sample-factory#127]
Hi @alex-petrenko , 
How can I produce fixed, deterministic episode on dmlab30, using sample factory? 
Is there any control parameters like random seed to be fixed?

**Comment by alex-petrenko** [comment]
Hi!
Can you explain what exactly you mean by a deterministic episode? I.e. you have a trained policy, and you want to evaluate it in a way that is consistent and repeatable?

Take a look at `enjoy` script: you will want to seed the environment (this line is currently commented out, but you can simply uncomment it): https://github.com/alex-petrenko/sample-factory/blob/486d5a6073d4c005ce3c9955567ca1546aed654c/sample_factory/algorithms/appo/enjoy_appo.py#L36

You will also need to modify the way we get actions from the policy. Currently actions are sampled from the distribution, but if we take argmax of action probabilities, we'll get a deterministic trajectory.
There's even a TODO about this here (should be a rather simple fix for a standard discrete distribution): https://github.com/alex-petrenko/sample-factory/blob/486d5a6073d4c005ce3c9955567ca1546aed654c/sample_factory/algorithms/appo/enjoy_appo.py#L83

Let me know if this helps.
