### ISSUE TITLE
Get a documentation website going

### ISSUE THREAD

**Issue by alex-petrenko** [alex-petrenko/sample-factory#146]
We definitely need something like ReadTheDocs for Sample Factory. Things are getting too sophisticated to keep documenting everything in README.

@wmFrank I think this can be a great next project for you after tests and coverage are working!

@edbeeching do you think we should use ReadTheDocs or are there better alternatives now?

**Comment by edbeeching** [comment]
ReadTheDocs should be good I think.

**Comment by alex-petrenko** [comment]
I discussed with Costa and they used this one: https://squidfunk.github.io/mkdocs-material/
I think it's also a good option.

**Comment by wmFrank** [comment]
Do you have a link to Costa's website?

**Comment by alex-petrenko** [comment]
https://docs.cleanrl.dev/

**Comment by alex-petrenko** [comment]
@wmFrank close issues when they're done!
Again, great work!
