### ISSUE TITLE
Add make format and make check-codestyle to git pre-commit

### ISSUE THREAD

**Issue by alex-petrenko** [alex-petrenko/sample-factory#160]
I recently updated the whole codebase to use black and isort formatting @edbeeching 

Since we've now automated code formatting, it makes sense to do it every time code is being committed to VCS.
Here's a short instruction I found that may be helpful: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

If we could make it such that anyone who clones the repo automatically gets the pre-commit hook, it'd be awesome.
@wmFrank since you are a king of CI, can you please do this thing? Not a very high priority, but ideally this should be done in the next few days.

**Comment by wmFrank** [comment]
Sounds good, I'll try it.

**Comment by alex-petrenko** [comment]
We also need to add `make check-codestyle` to CI checks alongside tests :)
