### ISSUE TITLE
[questio] What are the advances of SF2 over SF1?

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/sample-factory#178]
Would be great if it's noted somewhere.

**Comment by alex-petrenko** [comment]
Hi! It is still in development, we're of course planning to announce the full set of features once it's released! :)

For SF2 the whole codebase is rewritten pretty much from scratch, with a different mechanism for communication between processes.
This refactoring allowed us to efficiently integrate new classes of environments that provide observations entirely on the GPU, such as IsaacGym. On top of existing asynchronous learning we now support fully synchronous learning as well.
On top of that there are numerous new features, improved documentation, examples, and testing/CI system.

Please join Discord or subscribe to my Twitter for updates!
Not planning to support Windows (same reasons as before, GPU memory sharing does not work in Windows), but we're looking to add an evaluation worker feature in SF2 release or shortly after.
