### ISSUE TITLE
Issues running on server

### ISSUE THREAD

**Issue by alex404** [alex-petrenko/sample-factory#180]
Hey there, just wanted to mention I had issues running sample-factory on a server (connected through ssh, running in a docker container). After running one of the sample factory benchmark commands I would get

```
raise ImportError(
ImportError: 
    Cannot import pyglet.
    HINT: you can install pyglet directly via 'pip install pyglet'.
    But if you really just want to install all Gym dependencies and not have to think about it,
    'pip install -e .[all]' or 'pip install gym[all]' will do it.
```
even though I have pyglet installed.

I solved this by downgrading to `sample-factory=1.121.4`. This problem didn't arise on my home computer.

I've found a way around it, so I'm not sure if this is a priority with your efforts focused on SF2, but I just thought I'd mention it.

I'm glad to see work on SF continues!

**Comment by alex-petrenko** [comment]
Hi @alex404 , thank you for reporting this!
I believe in sf2 branch we actually added pyglet to dependency list explicitly. Installing gym[all] might indeed be a better way to go about it! 
@wmFrank can you please take a quick look to see if we should install gym[all], or maybe that would be too many dependencies which will complicate other things?

**Comment by wmFrank** [comment]
'pip install gym[all]' will install packages we don't need(specifically, it contains some environments we haven't tested on) and according to @andrewzhang505, installing mujoco-py will cause some problems in the newest version of gym. Personally, I think adding pyglet to the dependency list explicitly is a better way. Thanks for letting us know this @alex404.

**Comment by alex-petrenko** [comment]
@alex404 @wmFrank :+1: :+1: :+1:
