### ISSUE TITLE
[question] Mask Actions

### ISSUE THREAD

**Issue by CarlossShi** [alex-petrenko/sample-factory#196]
Hi,
I'm wondering if there is a way to mask actions? To be specific, what I need is to customize the decoder with a mask input so that its output has a probability of 0 for some actions.

**Comment by alex-petrenko** [comment]
Hi!
I don't think we have API for that, but it would be easiest to override an ActionParameterization class.
If we're talking about discrete actions, you can add an extra layer where the output of the last FC layer is multiplied by a mask and then a large negative value is added for masked actions (like -100). This should be equivalent to assigning 0 probability mass to masked actions and redistributing the remaining probability proportionally between the remaining actions.

Another solution that I've seen would be to give the entire probability distribution to the environment. Then actions can be sampled normally, and if action happens to be a masked one, we can choose the next most probable action (or resample from the remaining actions), plus add a small penalty for choosing the masked action.
I think if you also add the mask itself to the observations then the agent should relatively quickly learn not to choose masked actions.

Both solutions would require forking and modifying SF code, there's no existing API for this use case. Make sure to use branch "sf2", the model construction API is improved in the new version and it might simplify your task!
