### ISSUE TITLE
Videos (or Gifs) for README

### ISSUE THREAD

**Issue by alex-petrenko** [alex-petrenko/sample-factory#223]
@edbeeching it looks like Github's own Markdown renderer does not support `<video>`
Do you think we could make a set of Gifs that demonstrate some of the more interesting environments? I'm thinking Atari, Vizdoom, DMLab, Mujoco, IsaacGym locomotion and manipulation

Let me know what you think

**Comment by edbeeching** [comment]
@alex-petrenko  There is a sneaky way to do this. If you edit the readme in browser and drag and drop a video, it will embed it. 

For example:

https://user-images.githubusercontent.com/7275864/198523878-d511ea07-a68c-4ec6-bd7a-c8c5415ce9a5.mp4

**Comment by alex-petrenko** [comment]
Wow! A game changer :)

**Comment by alex-petrenko** [comment]
@edbeeching I tried adding Atari video (see at the end of Readme on sf2 branch), and it works, but there does not seem to be any way to control it's size or layout, or use autoplay/looping... I think maybe we should stick to Gifs for now as long as they're not very big?

**Comment by edbeeching** [comment]
Ah ok, let's stick with GIFs. Perhaps there are clever ways to format / tile the videos. But I agree that the simplest is to use a gif.

**Comment by alex-petrenko** [comment]
done
