### ISSUE TITLE
[question] OpenAI Gym Env?

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/sample-factory#23]
Hi, 
Is it possible to use with OpenAI Gym Env (non-image like Cartpole - yes I know it's very basic but I have a custom one that acts similar to Cartpole but can take forever to solve on a single machine)? If yes, can you suggest how-to?

Is it possible to use in Windows10 (with Nvidia GPU)?

Thanks!

**Comment by alex-petrenko** [comment]
You can use Sample Factory with any env that provides Gym-like interface.
Examples https://github.com/alex-petrenko/sample-factory/tree/master/examples show how to define your own custom env. If you custom env is just a OpenAI-Gym env, then make_env_func will be trivial, just a single line:

```
def make_env_func(full_env_name, cfg=None, env_config=None):
    return gym.make('Cartpole-V1')
```

You will also want to pass CLI parameters that will use the right model architecture for your task, which is probably `mlp`.

`--encoder_type=mlp --encode_subtype=mlp_mujoco --batch_size=256 --ppo_epochs=4 --nonlinearity=tanh --entropy_loss_coeff=0.0005 --policy_initialization=xavier_uniform --max_policy_lag=1000 --adaptive_stddev=False --initial_stddev=1.0 --hidden_size=64`

I would start with something like this

**Comment by alex-petrenko** [comment]
Perhaps support for the most standard OpenAI Gym wrappers should not require any code, just a simple CLI parameter. We wanted to support an advanced use case that allows users to define any kind of custom environment first.
This is definitely something to look at in the future.

**Comment by jarlva** [comment]
@alex-petrenko, thanks for the reply. I tried the solution on Windows10 with cuda GPU. As you may already guess, it failed in the faster_fifo import. Any way to compile it for Windows and run sample_factory in Win?

**Comment by tushartk** [comment]
@jarlva can you install faster-fifo 1.6.0 and check? I just pushed a new update to fix the failing import which was happening in the pip installation of faster-fifo

**Comment by jarlva** [comment]
@tushartk,  I get the error: cpp_faster_fifo/cpp_lib/faster_fifo.cpp(6): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

Full Error: 

(torch) C:\Users\Jake\py\sample-factory>pip install faster_fifo
Collecting faster_fifo
  Using cached faster-fifo-1.0.6.tar.gz (62 kB)
Building wheels for collected packages: faster-fifo
  Building wheel for faster-fifo (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Jake\miniconda3\envs\torch\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jake\\AppData\\Local\\Temp\\pip-install-uplh1am5\\faster-fifo\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jake\\AppData\\Local\\Temp\\pip-install-uplh1am5\\faster-fifo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Jake\AppData\Local\Temp\pip-wheel-0b7nsilg'
       cwd: C:\Users\Jake\AppData\Local\Temp\pip-install-uplh1am5\faster-fifo\
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'faster_fifo' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\cpp_faster_fifo
  creating build\temp.win-amd64-3.7\Release\cpp_faster_fifo\cpp_lib
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Icpp_faster_fifo/cpp_lib -IC:\Users\Jake\miniconda3\envs\torch\include -IC:\Users\Jake\miniconda3\envs\torch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpfaster_fifo.cpp /Fobuild\temp.win-amd64-3.7\Release\faster_fifo.obj
  faster_fifo.cpp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Icpp_faster_fifo/cpp_lib -IC:\Users\Jake\miniconda3\envs\torch\include -IC:\Users\Jake\miniconda3\envs\torch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpcpp_faster_fifo/cpp_lib/faster_fifo.cpp /Fobuild\temp.win-amd64-3.7\Release\cpp_faster_fifo/cpp_lib/faster_fifo.obj
  faster_fifo.cpp
  cpp_faster_fifo/cpp_lib/faster_fifo.cpp(6): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for faster-fifo
  Running setup.py clean for faster-fifo
Failed to build faster-fifo
Installing collected packages: faster-fifo
    Running setup.py install for faster-fifo ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Jake\miniconda3\envs\torch\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jake\\AppData\\Local\\Temp\\pip-install-uplh1am5\\faster-fifo\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jake\\AppData\\Local\\Temp\\pip-install-uplh1am5\\faster-fifo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Jake\AppData\Local\Temp\pip-record-hpzya75d\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Jake\miniconda3\envs\torch\Include\faster-fifo'
         cwd: C:\Users\Jake\AppData\Local\Temp\pip-install-uplh1am5\faster-fifo\
    Complete output (15 lines):
    running install
    running build
    running build_ext
    building 'faster_fifo' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cpp_faster_fifo
    creating build\temp.win-amd64-3.7\Release\cpp_faster_fifo\cpp_lib
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Icpp_faster_fifo/cpp_lib -IC:\Users\Jake\miniconda3\envs\torch\include -IC:\Users\Jake\miniconda3\envs\torch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpfaster_fifo.cpp /Fobuild\temp.win-amd64-3.7\Release\faster_fifo.obj
    faster_fifo.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Icpp_faster_fifo/cpp_lib -IC:\Users\Jake\miniconda3\envs\torch\include -IC:\Users\Jake\miniconda3\envs\torch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpcpp_faster_fifo/cpp_lib/faster_fifo.cpp /Fobuild\temp.win-amd64-3.7\Release\cpp_faster_fifo/cpp_lib/faster_fifo.obj
    faster_fifo.cpp
    cpp_faster_fifo/cpp_lib/faster_fifo.cpp(6): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Jake\miniconda3\envs\torch\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jake\\AppData\\Local\\Temp\\pip-install-uplh1am5\\faster-fifo\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jake\\AppData\\Local\\Temp\\pip-install-uplh1am5\\faster-fifo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Jake\AppData\Local\Temp\pip-record-hpzya75d\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Jake\miniconda3\envs\torch\Include\faster-fifo' Check the logs for full command output.

**Comment by alex-petrenko** [comment]
@tushartk @jarlva 
Sample Factory was never tested on Windows, and one would probably face multiple issues trying to make it work on this platform. Faster-fifo won't compile on Windows since it relies on POSIX API (Cygwin/MinGW could be an option but I wouldn't bother).
In fact, I would argue that at this time, Windows is not a great platform for deep learning experimentation.

I'd recommend switching to Ubuntu 18.04 for your deep learning projects. MacOS also might work for simple tests, although probably not for full-scale experiments.

You can take a look at Linux subsystem for Windows, I've heard recent versions got GPU support: https://docs.microsoft.com/en-us/windows/wsl/install-win10 
Please let me know if you have any success with this.

**Comment by jarlva** [comment]
I've used Windows a lot with RL with good results.
Yes, I'm familer with the option you mentioned and was about to test it. Until I read that it's buggy. Waiting for Win 2004 update to mature a bit and will experiment then. Thanks again.

**Comment by jarlva** [comment]
> You can use Sample Factory with any env that provides Gym-like interface.
> Examples https://github.com/alex-petrenko/sample-factory/tree/master/examples show how to define your own custom env. If you custom env is just a OpenAI-Gym env, then make_env_func will be trivial, just a single line:
> 
> ```
> def make_env_func(full_env_name, cfg=None, env_config=None):
>     return gym.make('Cartpole-V1')
> ```
> 
> You will also want to pass CLI parameters that will use the right model architecture for your task, which is probably `mlp`.
> 
> `--encoder_type=mlp --encode_subtype=mlp_mujoco --batch_size=256 --ppo_epochs=4 --nonlinearity=tanh --entropy_loss_coeff=0.0005 --policy_initialization=xavier_uniform --max_policy_lag=1000 --adaptive_stddev=False --initial_stddev=1.0 --hidden_size=64`
> 
> I would start with something like this


OK, got a Ubuntu 18.04 machine with gpu and followed the instructions above and got the error below. Would it be possible to get a simple CartPole-v1 sample code for clarity?


```
python test.py --experiment=expdir --env=mujoco_ --algo=APPO
[2020-07-01 11:30:52,080][08262] Default envs supported: dict_keys(['doom_', 'atari_', 'dmlab_', 'mujoco_', 'quadrotor_', 'MiniGrid'])
[2020-07-01 11:30:52,080][08262] Env registry entry created: my_custom_env_
[2020-07-01 11:30:52,197][08262] Env registry entry created: mujoco_
[2020-07-01 11:30:52,201][08262] Saved parameter configuration for experiment expdir not found!
[2020-07-01 11:30:52,201][08262] Starting experiment from scratch!
[2020-07-01 11:30:52,791][08262] Queried available GPUs: 0

Traceback (most recent call last):
  File "test.py", line 146, in <module>
    sys.exit(main())
  File "test.py", line 141, in main
    status = run_algorithm(cfg)
  File "/home/jake/py/sample-factory/run_algorithm.py", line 12, in run_algorithm
    algo = get_algo_class(cfg.algo)(cfg)
  File "/home/jake/py/sample-factory/algorithms/appo/appo.py", line 206, in __init__
    tmp_env = make_env_func(self.cfg, env_config=None)
  File "/home/jake/py/sample-factory/algorithms/appo/appo_utils.py", line 38, in make_env_func
    env = create_env(cfg.env, cfg=cfg, env_config=env_config)
  File "/home/jake/py/sample-factory/envs/create_env.py", line 22, in create_env
    env = env_registry_entry.make_env_func(full_env_name, cfg=cfg, env_config=env_config)
  File "/home/jake/py/sample-factory/envs/mujoco/mujoco_utils.py", line 25, in make_mujoco_env
    mujoco_spec = mujoco_env_by_name(env_name)
  File "/home/jake/py/sample-factory/envs/mujoco/mujoco_utils.py", line 21, in mujoco_env_by_name
    raise Exception('Unknown Mujoco env')
Exception: **Unknown Mujoco env**
```
Also tried with the above syntax: 

```
python test.py --experiment=expdir --env=mujoco_ --algo=APPO --encoder_type=mlp --encode_subtype=mlp_mujoco --batch_size=256 --ppo_epochs=4 --nonlinearity=tanh --entropy_loss_coeff=0.0005 --policy_initialization=xavier_uniform --max_policy_lag=1000 --adaptive_stddev=False --initial_stddev=1.0 --hidden_size=64
[2020-07-01 11:32:52,176][08284] Default envs supported: dict_keys(['doom_', 'atari_', 'dmlab_', 'mujoco_', 'quadrotor_', 'MiniGrid'])
[2020-07-01 11:32:52,176][08284] Env registry entry created: my_custom_env_
[2020-07-01 11:32:52,305][08284] Env registry entry created: mujoco_
usage: test.py [-h] --algo ALGO --env ENV --experiment EXPERIMENT
               [--experiments_root EXPERIMENTS_ROOT] [--train_dir TRAIN_DIR]
               [--device {gpu,cpu}] [--seed SEED]
<snip rest>
```

The file used was modified from the example file, with the make_env_func suggested above:
```python
import sys, gym
import numpy as np
from torch import nn

from algorithms.appo.model_utils import register_custom_encoder, EncoderBase, get_obs_shape, nonlinearity
from algorithms.utils.arguments import arg_parser, parse_args
from algorithms.utils.pytorch_utils import calc_num_elements
from envs.env_registry import global_env_registry
from run_algorithm import run_algorithm


def custom_parse_args(argv=None, evaluation=False):
    """
    Parse default SampleFactory arguments and add user-defined arguments on top.
    Allow to override argv for unit tests. Default value (None) means use sys.argv.
    Setting the evaluation flag to True adds additional CLI arguments for evaluating the policy (see the enjoy_ script).

    """
    parser = arg_parser(argv, evaluation=evaluation)

    # add custom args here
    parser.add_argument('--my_custom_arg', type=int, default=42, help='Any custom arguments users might define')

    # SampleFactory parse_args function does some additional processing (see comments there)
    cfg = parse_args(argv=argv, evaluation=evaluation, parser=parser)
    return cfg


def make_env_func(full_env_name, cfg=None, env_config=None):
    return gym.make('Cartpole-V1')

def add_extra_params_func(env, parser):
    """
    Specify any additional command line arguments for this family of custom environments.
    """
    p = parser
    p.add_argument('--custom_env_num_actions', default=10, type=int, help='Number of actions in my custom env')
    p.add_argument('--custom_env_episode_len', default=1000, type=int, help='Number of steps in the episode')


def override_default_params_func(env, parser):
    """
    Override default argument values for this family of environments.
    All experiments for environments from my_custom_env_ family will have these parameters unless
    different values are passed from command line.

    """
    parser.set_defaults(
        # encoder_custom='custom_env_encoder',
        hidden_size=128,
    )


def register_custom_components():
    global_env_registry().register_env(
        env_name_prefix='my_custom_env_',
        make_env_func=make_env_func, #make_custom_env_func,
        add_extra_params_func=add_extra_params_func,
        override_default_params_func=override_default_params_func,
    )

    # register_custom_encoder('custom_env_encoder', CustomEncoder)


def main():
    """Script entry point."""
    register_custom_components()
    cfg = custom_parse_args()
    status = run_algorithm(cfg)
    return status


if __name__ == '__main__':
    sys.exit(main())
```

**Comment by alex-petrenko** [comment]
Yes, thank you for your suggestion, this should indeed be more clear.

Please check out the latest version of the repo, I added files `train_gym_env.py` and `enjoy_gym_env.py` in the examples folder.
This command-line `python -m examples.train_gym_env --algo=APPO --use_rnn=False --num_envs_per_worker=20 --policy_workers_per_policy=2 --recurrence=1 --with_vtrace=False --batch_size=512 --hidden_size=256 --encoder_type=mlp --encoder_subtype=mlp_mujoco --reward_scale=0.1 --save_every_sec=10 --experiment_summaries_interval=10 --experiment=example_gym_cartpole-v1 --env=gym_CartPole-v1`
trains a policy for cartpole in about 30-40 seconds on my machine. Please also see comments in the file for details.

The current API for specifying environments is quite general, it enables a lot of flexibility but I also see that entry barrier is a bit high. The idea is that users can register _families_ of environments, and in these families, the environments have a lot in common. E.g. all Atari environments will have the same set of command-line parameters, and the same set of default hyperparams. This is a very typical use case in RL, and we found it very useful in our experimentation.

The name of the environment family should be the _prefix_ to the full environment name. The full environment name is then routed to the user-defined `make_env_func()` which can do with it what it pleases. The most typical use case is to split the full name into the family name and the unique environment-specific name. In our case environment gym_CartPole-v1 means env `CartPole-v1` belonging to env family `gym_`

If you have suggestions on how to improve this interface and make it easier to use, I'd appreciate it. Perhaps splitting the env family name and env name into two distinct CLI variables is a good start.

**Comment by jarlva** [comment]
Alex, I appriciate your effort adding the code! That's exactly what I was after.
I notice the gpu is hovering between 20-35%. Which is much better utilization than any other RL software I've used. This is an amazing accomplishment!

Would it be possible to take a look at the following questions:
1. Running cartpole-v1 usually takes up to 5 minutes with only a cpu (like using on stable-baselines with much lower frame speed). Was wondering for the reason it takes sample-factory 10 minutes using both cpu/gpu?

2. What are the plans for sample-factory repository? Are there plans to maintain it or expand on it?

3. How to turn on tensorboard logging to real-time monitor?

4. Trying to watch results I got (have pyglet 1.5):
```bash
python -m examples.enjoy_gym_env  --experiment=example_gym_cartpole-v1 --env=gym_CartPole-v1
[2020-07-01 17:14:59,518][24864] Default env families supported: ['doom_*', 'atari_*', 'dmlab_*', 'mujoco_*', 'quadrotor_*', 'MiniGrid*']
[2020-07-01 17:14:59,519][24864] Env registry entry created: gym_
[2020-07-01 17:14:59,620][24864] Loading existing experiment configuration from /home/jake/py/train_dir/example_gym_cartpole-v1/cfg.json
[2020-07-01 17:14:59,620][24864] Adding new argument 'fps'=0 that is not in the saved config file!
[2020-07-01 17:14:59,621][24864] Adding new argument 'render_action_repeat'=None that is not in the saved config file!
[2020-07-01 17:14:59,621][24864] Adding new argument 'record_to'='/home/jake/py/../recs' that is not in the saved config file!
[2020-07-01 17:14:59,621][24864] Adding new argument 'no_render'=False that is not in the saved config file!
[2020-07-01 17:14:59,621][24864] Adding new argument 'policy_index'=0 that is not in the saved config file!
[2020-07-01 17:14:59,621][24864] Adding new argument 'continuous_actions_sample'=True that is not in the saved config file!
[2020-07-01 17:14:59,621][24864] Not using action repeat!
[2020-07-01 17:14:59,621][24864] Using action repeat 1 during evaluation
[2020-07-01 17:15:01,570][24864] Loading state from checkpoint /home/jake/py/train_dir/example_gym_cartpole-v1/checkpoint_p0/checkpoint_000004826_2470912.pth...
Traceback (most recent call last):
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jake/py/sample-factory/examples/enjoy_gym_env.py", line 16, in <module>
    sys.exit(main())
  File "/home/jake/py/sample-factory/examples/enjoy_gym_env.py", line 11, in main
    status = enjoy(cfg)
  File "/home/jake/py/sample-factory/algorithms/appo/enjoy_appo.py", line 117, in enjoy
    env.render()
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py", line 150, in render
    from gym.envs.classic_control import rendering
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/pyglet/window/__init__.py", line 632, in __init__
    self._create()
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 346, in _create
    self.set_caption(self._caption)
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 505, in set_caption
    self._set_text_property('_NET_WM_NAME', caption)
  File "/home/jake/miniconda3/envs/sample-factory/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 779, in _set_text_property
    raise XlibException('Could not create UTF8 text property')
pyglet.window.xlib.XlibException: Could not create UTF8 text property
```

**Comment by alex-petrenko** [comment]
I don't think you should be concerned about GPU utilization in a problem like this. The neural network involved is truly tiny and no matter what you do with the algorithm you probably won't be able to reach effective hardware usage. In fact, CPU can sometimes be even faster on narrow NNs like this. 

`Running cartpole-v1 usually takes up to 5 minutes with only a cpu. Was wondering what is the reason it takes sample-factory 10 minutes using both cpu/gpu?`
On my machine, it takes well under a minute to train to convergence on Cartpole, and I haven't really optimized the command line for that (might be better with more epochs).
What hardware are you using? What FPS are you generally seeing in the command line output?

`What are the plans for sample-factory repository? Are there plans to maintain it or expand on it?
`
This codebase is currently being used for new research projects, so it is reasonable to expect further improvements. Most likely in terms of further optimization and multi-machine training.

`How to turn on tensorboard logging for real-time monitoring?`
Please refer to the README section
https://github.com/alex-petrenko/sample-factory#monitoring-training-sessions

`Trying to watch results I get (have pyglet 1.5)`
Are you trying to run this on a server or locally? The error is related to rendering, the process isn't able to create a window, which can happen when there's no monitor connected. I don't think it is a problem of Sample Factory at this point, you should debug render() function of your environment.
Command line parameter `--no_render` for the enjoy script can help you run evaluation without rendering.

**Comment by jarlva** [comment]
I'm glad to hear you plan to maintain it. I plan to adopt it. More documentation would be greatly appreciated!

Regarding cartpole, I'm almost there. See below after 12 minutes it reached a score of ~178. Using same hardware in windows (no gpu) I can reach 500 score in less than 3 minutes. The avg fps is ~700. The syntax is (have 2core cpu). What am I doing wrong?

```
python -m examples.train_gym_env --algo=APPO --use_rnn=False --num_envs_per_worker=2 
--policy_workers_per_policy=2  --recurrence=1 --with_vtrace=False --batch_size=512 --hidden_size=64 
--encoder_type=mlp --encoder_subtype=mlp_mujoco --reward_scale=0.1 --save_every_sec=10
--experiment_summaries_interval=5 --experiment=example_gym_cartpole-v1
 --env=gym_CartPole-v1 --train_dir=~\py\files\train_dir

[2020-07-02 08:52:27,918][04846] Env runner 0, CPU aff. [0], rollouts 8857: timing wait_actor: 0.0000, waiting: 88.8107, reset: 0.0040, save_policy_outputs: 29.0223, env_step: 25.1541, overhead: 48.7757, complete_rollouts: 3.0284, enqueue_policy_requests: 537.3742, one_step: 0.0021, work: 694.8426, wait_buffers: 7.3504
[2020-07-02 08:52:27,918][04848] Env runner 1, CPU aff. [1], rollouts 8970: timing wait_actor: 0.0017, waiting: 99.4780, reset: 0.0335, save_policy_outputs: 27.3675, env_step: 25.1721, overhead: 47.7544, complete_rollouts: 8.0360, enqueue_policy_requests: 537.7437, one_step: 0.0005, work: 684.1741, wait_buffers: 2.3086
[2020-07-02 08:52:28,043][04845] Policy worker avg. requests 1.04, timing: init: 2.1041, wait_policy_total: 247.3856, wait_policy: 0.0051, handle_policy_step: 536.1871, one_step: 0.0000, deserialize: 2.7871, obs_to_device: 34.0276, stack: 68.1856, forward: 351.4150, postprocess: 23.9451, weight_update: 0.0005
[2020-07-02 08:52:28,044][04844] Policy worker avg. requests 1.00, timing: init: 2.1023, wait_policy_total: 249.8297, wait_policy: 0.0051, handle_policy_step: 534.5490, one_step: 0.0000, deserialize: 2.7418, obs_to_device: 34.3358, stack: 69.8506, forward: 349.1959, postprocess: 23.6450, weight_update: 0.0005
[2020-07-02 08:52:28,145][04830] GPU learner timing: extract: 0.5983, buffers: 0.0882, calc_gae: 1.6209, batching: 9.2988, buff_ready: 0.3662, tensors_gpu_float: 1.1863, squeeze: 0.0213, prepare: 12.9585, batcher_mem: 1.5662
[2020-07-02 08:52:28,451][04830] Train loop timing: init: 1.8398, train_wait: 0.4616, epoch_init: 0.0055, minibatch_init: 0.0023, forward_head: 3.1918, bptt_initial: 1.5796, bptt_forward_core: 0.0154, bptt: 0.0434, tail: 3.3532, losses: 2.0887, clip: 1.7157, update: 13.0571, after_optimizer: 6.0947, train: 31.7106
[2020-07-02 08:52:28,614][04809] Workers joined!
[2020-07-02 08:52:28,614][04809] Collected {0: 569856}, FPS: 681.3
[2020-07-02 08:52:28,614][04809] Timing: experience: 835.6249
[2020-07-02 08:52:29,115][04809] Done!
```

![Screenshot_2020-07-02 TensorBoard](https://user-images.githubusercontent.com/26058035/86321984-bf34e680-bc42-11ea-842f-eb2649280388.png)

**Comment by alex-petrenko** [comment]
I just ran this experiment on my laptop (a different machine), and with the settings that I provided it converges in about 40 seconds. GPU does not seem to speed up the process all that much, performance is about the same.

![image](https://user-images.githubusercontent.com/5497775/86324387-5ffbb580-bbf3-11ea-9ab6-6a27d3fc18a4.png)

With slightly different settings (smaller batch, 4 epochs instead of 1), it converges in about 25 seconds.

`python -m examples.train_gym_env --algo=APPO --use_rnn=False --num_envs_per_worker=20 --policy_workers_per_policy=2 --recurrence=1 --with_vtrace=False --batch_size=256 --num_batches_per_iteration=4 --hidden_size=256 --encoder_type=mlp --encoder_subtype=mlp_mujoco --reward_scale=0.1 --save_every_sec=10 --experiment_summaries_interval=1 --experiment=example_gym_cartpole-v1-4e --env=gym_CartPole-v1 --ppo_epochs=4 --max_policy_lag=100000`

This laptop has 6 physical CPU cores.
I'd say this task is entirely CPU bound. Hate to say it but most likely your machine isn't super well suited for deep RL experimentation. CPU is very important for RL, I'd suggest investing in as many cores as you can.
Although the number 600FPS still seems awfully low. Even with just two workers (--num_workers=2) I get 7-8K FPS on my laptop. What is the throughput without GPU? What are the specific models of your CPU/GPU?

**Comment by jarlva** [comment]
Alex, I used your latest syntax and got 3200 fps, reaching 500 score after 20 sec! Awesome! And that with a 5 year old 2.9Ghz dual core cpu and 1050 TI gpu! I plan to run the actual training on something like vast.ai. 

Any chance to document the various syntax args (can be a simple readme text)?

Thank you again! Jake

**Comment by alex-petrenko** [comment]
@jarlva all parameters have comprehensive help strings in the source code.
In particular take a look at files algorithm.py and appo.py and the configuration section in the README.

For the list of all parameters for the algortithm-env combination you can just pass an incorrect argument, e.g.
`python -m algorithms.appo.train_appo --algo APPO --env doom_basic --experiment=test --x` Feel free to search the parameter names in the codebase, they have comprehensive explanations.

There is definitely room for improvement here. I'll probably add a parameter to output all help strings to console, like --help.

**Comment by alex-petrenko** [comment]
Created a separate issue for this https://github.com/alex-petrenko/sample-factory/issues/28

**Comment by jarlva** [comment]
Thanks!
