### ISSUE TITLE
[question] gpu benefit?

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/sample-factory#24]
In another RL training with a gpu I noticed that the gpu utilization is no more than ~10% (both pytorch and TF). I assume it’s because python is busy with the env and agent logic. Planning to buy a laptop but not sure if it’s worth paying more for discrete Nvidia gpu if utilization is that low. 

My question is: does sample-factory really use the gpu and what is a typical utilization %?

Thanks.

**Comment by alex-petrenko** [comment]
Improving hardware utilization was one of the major points behind the creation of Sample Factory.
That said, GPU utilization in a particular experiment will depend on so many factors that I can't possibly tell you any kind of specific number.

As long as you're working with pixel-based environments, it is definitely worth investing in a GPU, as you can achieve much higher throughput. And you can definitely expect more GPU utilization with Sample Factory compared to analogous software. GPUs help massively in our experiments with VizDoom, Atari and DMLab.

If your main use case is environments with low-dimensional inputs and/or very small models, GPU training isn't going to make that much difference.

**Comment by jarlva** [comment]
Cool! Thanks!
