### ISSUE TITLE
[advice]?

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/sample-factory#252]
Hi, recently upgraded to a Ryzen 7950 (16 cores/32 threads, PCI-E 5) and converted to SF2. The Nvidia 1050 peaks at ~75% (using NVIDIA-SMI) while the cpu's are not really working hard. It used to be the other way around. I'm able to average 175,000 fps. Kudus to Alex and the developers!!

Would you say that now my bottleneck is the GPU? If yes which GPU is best for the buck (was thinking of 3060 TI)?

Thanks in advance.

**Comment by alex-petrenko** [comment]
Hi @jarlva !

To accommodate your new hardware you might consider changing some settings. There's some new info here that you might want to check out: https://www.samplefactory.dev/02-configuration/configuration/#key-parameters

The most obvious suggestions:
* increase the number of workers `--num_workers`, ideally to 32
* increase batch size
* follow suggestions from here https://www.samplefactory.dev/07-advanced-topics/policy-lag/ to keep your policy lag at bay with new settings

No ML workload is generally guaranteed to max out your GPU. I'd say 75% is a very good GPU utilization actually.
But the suggestions above can help make your CPU work harder.

I'm not sure about GPU buying advice :) It really depends on your budget and tasks. 3060Ti is not the worst choice, but make sure you'll have enough VRAM for what you're doing!

**Comment by jarlva** [comment]
I'll review the notes. Thanks again!
P.s., is there a possibility to implement MuzZero at some point?

**Comment by alex-petrenko** [comment]
Probably not at this time, sorry. I'd be happy to review code / provide suggestions though!

**Comment by jarlva** [comment]
I'm not at that level :) However, there is this code: https://github.com/werner-duvaud/muzero-general
