### ISSUE TITLE
Error using "--encoder_mlp_layers"

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/sample-factory#258]
Hey, I'd like to change the default model layers on a custom gym environment on SF2. The "--encoder_mlp_layers" switch errors: `train_gym_env.py: error: argument --encoder_mlp_layers: invalid int value: '[1024,512]'`

Using the sample command line with the encoder switch appended:
`python -m sf_examples.train_gym_env --algo=APPO --use_rnn=False --num_envs_per_worker=20 --policy_workers_per_policy=2 --recurrence=1 --with_vtrace=False --batch_size=512 --reward_scale=0.1 --save_every_sec=10 --experiment_summaries_interval=10 --experiment=example_gym_cartpole-v1 --env=CartPole-v1 --encoder_mlp_layers=[1024,512]`

also tried: 
```
--encoder_mlp_layers="[1024,512]"
--encoder_mlp_layers=[[1024,512]]
```

**Comment by alex-petrenko** [comment]
Hi! The correct syntax is `--encoder_mlp_layers 128 256 512`
Omit the `=` sign and just provide a list of numbers for the layer sizes. This is the standard syntax for Python's list-type CLI arguments.

I will add a note to the documentation about this! :)
