### ISSUE TITLE
ValueError in colab

### ISSUE THREAD

**Issue by amrzv** [alex-petrenko/sample-factory#261]
Hi.
When running `samplefactory_hub_example.ipynb` notebook in colab the `ValueError` raises:
![image](https://user-images.githubusercontent.com/36787333/212562627-24829a22-84fe-468b-92d0-0a65bdebc223.png)

Seems that there is a bug in `sample_factory.utils.gpu_utils.py`.

**Comment by alex-petrenko** [comment]
looks like `CUDA_VISIBLE_DEVICES` contains something like `0,\n` and we don't expect this.

**Comment by alex-petrenko** [comment]
Pushed a small fix, see if this helps :)

https://github.com/alex-petrenko/sample-factory/commit/7509cc4b37cbf5b7b541ea0dda49cbad1152c8fe

**Comment by amrzv** [comment]
I forgot to mention, that this error was raised when running in colab without GPU. Now, when running in colab without GPU the `ValueError` above is gone, but next another raises:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/36787333/212642718-f3ef3d62-508c-4a1a-922f-588a2e95860b.png">
Seems that the device should be manually set before in `cfg`:
`cfg.device = 'gpu' if torch.cuda.is_available() else 'cpu'`

However, when I add this line to `cfg`, restart notebook and run again I still observe device=='gpu' in logging information:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/36787333/212643890-6d2e34a1-9648-427f-9fe5-a82d9602c74f.png">

I'm not sure if everything is supposed to work on CPU.

When running in colab with GPU whole notebook works without errors.

**Comment by andrewzhang505** [comment]
From the screenshot, it looks like the notebook is loading an old experiment where the cfg still has the device set to gpu. Could you try changing the `experiment_name` and running again with `cfg.device=cpu`? Alternatively, you can add the command line `--restart_behavior=restart` to the argv to wipe out the old experiment

**Comment by amrzv** [comment]
I cleared the local dir, restarted the kernel and run again. Now notebook works without errors:
![image](https://user-images.githubusercontent.com/36787333/212678131-43c42d33-b900-4b8d-88c9-06f0feb4b5f3.png)

So, probably this line should be added as on the screenshot:
`cfg.device = 'gpu' if torch.cuda.is_available() else 'cpu'`

**Comment by alex-petrenko** [comment]
@andrewzhang505 thank you for fixing this!

@amrzv thank you for reporting the issue!
Are you generally able to run serious multi-process configurations of Sample Factory in Colab Notebooks? I have no experience with this myself, and I know that Jupiter notebooks had some issues with multiprocessing preventing people from unlocking the full speed and power of the codebase.

I'd be happy to know if Colab solves this issue.

Also, certain types of environments work really well with a single-process synchronous configuration (such as Brax and IsaacGym). I can imagine interactive notebooks are great for these environments.

**Comment by amrzv** [comment]
I would say that Colab environment has the same limitations as Jupyter.
So, what about multiprocessing, the behaviour and issues which you mentioned are the same in Colab.
