### ISSUE TITLE
Non-symmetric action/observation spaces for multiagent environments?

### ISSUE THREAD

**Issue by MatthewCWeston** [alex-petrenko/sample-factory#266]
I've been trying to write a wrapper for several popular MARL environments (in particular, the multiagent particle environments from the MADDPG paper) using the custom multiagent environment template, but it seems to only support a single action space for all agents. Have I misread the code, or are only symmetric action spaces supported at present?

**Comment by alex-petrenko** [comment]
Yeah, this is one thing we currently don't explicitly support, SF expects mostly homogenous agents.
In the past, my recommendation was to make a bigger action space and have different policies use subsets of it, and you can do the same for observations.

It would not be that difficult to modify the code to support multiple different obs/action spaces for different policies. I consciously decided not to do it in this version cause the code is already pretty messy around the tensor shapes and data flow. But maybe in future versions :)

Sorry if this is not the answer you expected. Sometimes you have to make compromises between performance, supported features, and development time.

**Comment by MatthewCWeston** [comment]
No worries. I'll check around similar libraries, and maybe take a shot at implementing it myself, if that looks like the cleanest option.
