### ISSUE TITLE
Add git commit hash to cfg.json

### ISSUE THREAD

**Issue by alex-petrenko** [alex-petrenko/sample-factory#32]
Also save diff to some separate file in the experiment folder.
This is great for reproducibility.

**Comment by tushartk** [comment]
Oh yeah, this is the next task after the sample environment issue

**Comment by alex-petrenko** [comment]
Just wanted to document before I forgot about it

чт, 16 июл. 2020 г. в 00:07, Tushar K <notifications@github.com>:
