### ISSUE TITLE
Memory leak on the actor worker?

### ISSUE THREAD

**Issue by alex-petrenko** [alex-petrenko/sample-factory#34]
In my experiments with LunarLanderContinuous I spotted a constant memory increase on the actor workers. We need to find the reason for it and fix it.

Please first of all try to see if it only reproduces on LunarLander or on other envs too (e.g. doom)

**Comment by alex-petrenko** [comment]
![image](https://user-images.githubusercontent.com/5497775/87885177-becd7700-c9c8-11ea-880c-579ed32dff26.png)

**Comment by Zhehui-Huang** [comment]
I tested it in three environments. Vizdoom(basic), Gym(cartpole-v0), Mujoco(hopper). And the result shows that there is no memory leak on the actor worker in these environments.
![memory_cartpole](https://user-images.githubusercontent.com/30305127/87976769-868a6f00-ca82-11ea-9041-c95432b2917f.png)
![memory_doom_basic](https://user-images.githubusercontent.com/30305127/87976770-868a6f00-ca82-11ea-9d24-5eca44db2659.png)
![memory_mujoco_hopper-1](https://user-images.githubusercontent.com/30305127/87976771-87230580-ca82-11ea-82ad-9a38e39fb5b3.png)

**Comment by alex-petrenko** [comment]
Please try to find why it leaks with the lunar lander

**Comment by Zhehui-Huang** [comment]
It should be the bug of Lunarlander environment itself.  
The way to solve it is to change fixtureDef as a global variable.
Such as:
[lunar_lander.txt](https://github.com/alex-petrenko/sample-factory/files/4970079/lunar_lander.txt)
Default lunar_lander.py
https://github.com/openai/gym/blob/master/gym/envs/box2d/lunar_lander.py

More details. https://github.com/openai/gym/issues/1882
https://github.com/openai/gym/pull/997
https://github.com/openai/gym/issues/980
https://github.com/openai/gym/pull/1509

**Comment by alex-petrenko** [comment]
Cool! I'm glad this is not on our side!
