### ISSUE TITLE
Adding an aysnc Rainbow-style DQN to the algorithms default

### ISSUE THREAD

**Issue by neevparikh** [alex-petrenko/sample-factory#47]
Hi all, 

I was wondering if you guys would be interested in adding an async Rainbow DQN that fits into this framework. I would like to contribute towards such a thing and ideally have it be there for others to use later on.

**Comment by jarlva** [comment]
Any chance for IMPALA?

**Comment by neevparikh** [comment]
Isn't IMPALA intended for distributed training? And the V-trace parts are already implemented I think no?

**Comment by alex-petrenko** [comment]
We were not planning to add off-policy algorithms at this point, but the contributions are of course welcome!
I'd be happy to review code and guide you.

If you're interested in off-policy algorithms, I'd suggest R2D2 which currently stands as SOTA in off-policy learning.
Of course, if something like this is implemented in Sample Factory, it should adhere to the same ideals, namely the uncompromised performance. In particular, I'd suggest largely reusing the existing actor-policy worker infrastracture for sampling, storing experience replay in shared memory, and perhaps writing a new learner class (probably need to refactor the existing learner to reuse some code).

**Comment by alex-petrenko** [comment]
Beware of dragons ahead though! :) SampleFactory was created with performance in mind, rather than customizability!
Although some architecture to support multiple algorithms is already in place, e.g. the run_algorithm.py script

**Comment by alex-petrenko** [comment]
@jarlva current implementation is very similar to IMPALA. I believe if you disable PPO-clipping and value clipping, the algorithm will be exactly the single-machine version of IMPALA.

**Comment by alex-petrenko** [comment]
@neevparikh 
Research-wise, there is an interesting question of whether DQN variants can approach or beat the performance of PPO on the tasks we were using in the paper.
In particular, they have a very complex action space, in the deathmatch variant it's about 10000 different actions. Can you learn a Q-function for that? What is the right way to support such action distributions in off-policy algorithms?
Do you just learn a separate Q-function for every action subspace?

I'd be very curious to find out.

**Comment by neevparikh** [comment]
Yeah, I'm not sure how well it would work. It'd be interesting to find out.

**Comment by neevparikh** [comment]
> If you're interested in off-policy algorithms, I'd suggest R2D2 which currently stands as SOTA in off-policy learning.

Regarding R2D2 vs AsyncDQN/Rainbow, my thoughts were I would start with the simplest working version of asyncDQN (which we know won't work as well as APPO). This is because most of the work (on my end) probably lies in getting familiar with the codebase and the subsequent refactoring that will ensue. 

My hope is that making things more modular and easier to extend is itself valuable for this repo and then I can definitely investigate R2D2 and off-policy algorithms in general

**Comment by alex-petrenko** [comment]
It makes sense to start with more standard well-tuned DQN.
After this adding R2D2 should not be hard, the major parts are the same anyway. The key difference there is the RNN warmup.

I'm not sure about 50x (the other framework must be really slow for that to be possible). I think you can expect similar speedup as what SampleFactory APPO gives vs that implementation.

This also depends, of course, on how many times you learn from your experience. APPO currenly does 1 SGD step by default, and it is not uncommon in off-policy algorithms to do significantly more than that.
Although, I remember from reading R2D2 they do something like 1.4 times on average per sample.

**Comment by jarlva** [comment]
@alex-petrenko, you mean to set  ppo_clip_value=0 , ppo_clip_ratio=0?

That's all that's needed to switch tp IMPALA?

> @jarlva current implementation is very similar to IMPALA. I believe if you disable PPO-clipping and value clipping, the algorithm will be exactly the single-machine version of IMPALA.

**Comment by alex-petrenko** [comment]
@jarlva the opposite, you need to change ppo_clip_value and clip_ratio to some large number, like 100.0
This will effectively mean "no clipping". Yes, with v_trace enabled this will give you the IMPALA algorithm.

Why you'd want to do this is a different question, because IMPALA and PPO-clipping work together perfectly fine.

**Comment by jarlva** [comment]
> Why you'd want to do this is a different question, because IMPALA and PPO-clipping work together perfectly fine.

I read that IMPALA is better than PPO.

**Comment by alex-petrenko** [comment]
@jarlva 
what I mean is that there shouldn't be "better" or "worse" because IMPALA and PPO are not two different algorithms. They are two different heuristics added on top of standard on-policy actor-critic.
IMPALA introduces the V-trace value function objective, and PPO clips the probability ratios to prevent destructive policy updates. In SampleFactory you can use these together or separately.

Again, if IMPALA without PPO clipping works better for you, you can easily disable the clipping via parameters mentioned above.

**Comment by jarlva** [comment]
@alex-petrenko , thanks for the clarification.
I look forward to continue to adopt SF project and see it grow and mature.  Personally, before new algo, I'd love to see a rudimentary mechanism that optimizes the various  arg options (core/workers/learner/etc) based on hardware. Sometimes I use a 30 core machine that is slower than a 20-core and it can take a long time to get all the switches right.

**Comment by vwxyzjn** [comment]
As to whether DQN can be applied to the domains in your paper, you may find these reference interesting: https://arxiv.org/pdf/1711.08946.pdf, https://skatgame.net/mburo/aiide20ws/papers/paper4-cameraready.pdf.

I would be quite interested in implementing DQN or Apex-DQN in a similar fashion as sample-factory.

**Comment by alex-petrenko** [comment]
@vwxyzjn thank you for these links! I haven't seen this before.
I guess it's pretty obvious that Q-learning can indeed be used with multiple action heads, it's just I don't have the intuition on how this will scale. It might in fact be the case that Q-learning is even better in these scenarios.

**Comment by alex-petrenko** [comment]
```I would be quite interested in implementing DQN or Apex-DQN in a similar fashion as sample-factory.```

Please let me know if I can support or help in any way!

**Comment by neevparikh** [comment]
I've been quite busy with work over the last few months but I'm still very interested in helping out

**Comment by lmBored** [comment]
@alex-petrenko I’ve been using Sample Factory recently, noticed I needed an off-policy algorithm for comparison, and saw the need for a DQN implementation in this issue. I have implemented async DQN (performance-wise it's faster than original APPO), are you still interested in reviewing this? If yes, I will open a PR

**Comment by alex-petrenko** [comment]
@lmBored for certain personal reasons I'm not actively working on this repo, I think the best option might be to fork the repo and continue developing off-policy methods in the fork. I'd be happy to share your work on X or discord!

If you think that it naturally integrates with the rest of SF with minimal changes I'd be happy to review the PR though. Your judgement!

**Comment by lmBored** [comment]
@alex-petrenko Thank you for replying! It's actually minimal changes so I'm happy to submit a PR. Also I'd really love to get a third perspective on my approach :)
