### ISSUE TITLE
Atari Hyper-parameters 

### ISSUE THREAD

**Issue by IouJenLiu** [alex-petrenko/sample-factory#51]
Hi 

Could I have the hyper-parameters used in the Atari experiments of the paper?

Thanks!

**Comment by alex-petrenko** [comment]
Hi, sorry, didn't see the message right away.
We didn't really train any atari policies for the paper, but for max trhoughput numbers we used this command line:

```python -m algorithms.appo.train_appo --env=atari_breakout --algo=APPO --env_frameskip=4 --use_rnn=True --num_workers=72 --num_envs_per_worker=24 --num_policies=1 --ppo_epochs=1 --rollout=32 --recurrence=32 --batch_size=6144 --benchmark=False --policy_workers_per_policy=2 --worker_num_splits=2 --decorrelate_experience_max_seconds=10 --env_framestack=4 --max_grad_norm=0.0 --experiment=fps_atari_break_72_24_6144_id_1_lstm --nonlinearity=relu --rnn_type=lstm```

Please let me know if you have any additional questions!

**Comment by alex-petrenko** [comment]
@Sino-Huang FYI here are some details on our recent Atari experiments https://alex-petrenko.github.io/sample-factory/environment-integrations/atari/#list-of-supported-environments
We used the same hyperparameters as CleanRL / rl_games to be able to match their results.

HuggingFace links or WandB can give you full list of parameters (i.e. see cfg.json on HuggingFace  https://huggingface.co/wmFrank/sample-factory-2-atari-breakout/tree/main)
