### ISSUE TITLE
[question] MuZero anyone?

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/sample-factory#75]
Hey all,

Wondering if you've seen MuZero, the latest from Deepmind? Is it something that can improve SF speed/results? I've seen some implementations on github but not knowledgeable enough to implant them in SF.

Below is a comparrison chart from https://arxiv.org/pdf/1911.08265.pdf 

![image](https://user-images.githubusercontent.com/26058035/103151621-5610d480-4788-11eb-9c03-e7f99ad3972d.png)

**Comment by alex-petrenko** [comment]
I've seen it, in fact, this is something that I would like to work on in
the future.

This is a completely different RL algorithm though, no relation to SF
whatsoever. Probably would have to be implemented from scratch.

сб, 26 дек. 2020 г. в 13:08, jarlva <notifications@github.com>:

**Comment by jarlva** [comment]
If you need to test on Windows, let me know 😉
